feat(ci): v1 (#248)
* feat(ci): v1

---------

Signed-off-by: Luca Bello <36242061+lucabello@users.noreply.github.com>

diff --git a/.github/workflows/charm-promote.yaml b/.github/workflows/charm-promote.yaml
--- a/.github/workflows/charm-promote.yaml
+++ b/.github/workflows/charm-promote.yaml
@@ -32,14 +32,14 @@ jobs:
           PROMOTE_FROM: ${{ github.event.inputs.promotion }}
         run: |
           if [ "${PROMOTE_FROM}" == "edge -> beta" ]; then
-            echo "promote-from=edge" >> ${GITHUB_ENV}
-            echo "promote-to=beta" >> ${GITHUB_ENV}
+            echo "promote-from=edge" >> "$GITHUB_ENV"
+            echo "promote-to=beta" >> "$GITHUB_ENV"
           elif [ "${PROMOTE_FROM}" == "beta -> candidate" ]; then
-            echo "promote-from=beta" >> ${GITHUB_ENV}
-            echo "promote-to=candidate" >> ${GITHUB_ENV}
+            echo "promote-from=beta" >> "$GITHUB_ENV"
+            echo "promote-to=candidate" >> "$GITHUB_ENV"
           elif [ "${PROMOTE_FROM}" == "candidate -> stable" ]; then
-            echo "promote-from=candidate" >> ${GITHUB_ENV}
-            echo "promote-to=stable" >> ${GITHUB_ENV}
+            echo "promote-from=candidate" >> "$GITHUB_ENV"
+            echo "promote-to=stable" >> "$GITHUB_ENV"
           fi
       - name: Install a specific version of uv
         uses: astral-sh/setup-uv@v4
@@ -53,11 +53,12 @@ jobs:
       - name: Promote charm
         env:
           CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
+          CHARM_PATH: "${{ inputs.charm-path }}"
         run: |
           # Read the charm name from charmcraft.yaml / metadata.yaml
-          cd ${{ inputs.charm-path }}
+          cd "$CHARM_PATH"
           charm_name=$(yq .name metadata.yaml 2>/dev/null || yq .name charmcraft.yaml)
-          if [[ $charm_name = "" ]]; then echo "Error: can't extract the charm name." && exit 1; fi
+          if [[ "$charm_name" = "" ]]; then echo "Error: can't extract the charm name." && exit 1; fi
           # Run `noctua charm promote`
           noctua charm promote "$charm_name" \
             --from=${{ inputs.track }}/${{ env.promote-from }}
