feat: use noctua in charm promotions

diff --git a/.github/workflows/charm-promote.yaml b/.github/workflows/charm-promote.yaml
--- a/.github/workflows/charm-promote.yaml
+++ b/.github/workflows/charm-promote.yaml
@@ -23,7 +23,7 @@ on:
 jobs:
   promote:
     name: Promote Charm
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -41,11 +41,19 @@ jobs:
             echo "promote-from=candidate" >> ${GITHUB_ENV}
             echo "promote-to=stable" >> ${GITHUB_ENV}
           fi
-      - name: Promote Charm
-        uses: canonical/charming-actions/promote-charm@2.6.0
-        with:
-          charm-path: ${{ inputs.charm-path }}
-          credentials: ${{ secrets.CHARMHUB_TOKEN }}
-          destination-channel: ${{ github.event.inputs.track }}/${{ env.promote-to }}
-          origin-channel: ${{ github.event.inputs.track }}/${{ env.promote-from }}
-          charmcraft-channel: latest/stable
+      - name: Install dependencies
+        run: |
+          sudo snap install astral-uv
+          # Install noctua
+          uv tool update-shell
+          uv tool install git+https://github.com/lucabello/noctua
+      - name: Promote charm
+        run: |
+          # Read the charm name from charmcraft.yaml / metadata.yaml
+          cd ${{ inputs.charm-path }}
+          charm_name=$((yq .name metadata.yaml 2>/dev/null || yq .name charmcraft.yaml) | tr - _)
+          if [[ $charm_name = "" ]]; then echo "Error: can't extract the charm name." && exit 1; fi
+          # Run `noctua charm promote`
+          export CHARMHUB_TOKEN="${{ secrets.CHARMHUB_TOKEN }}"
+          noctua charm promote "$charm_name" \
+            --from=${{ github.event.inputs.track }}/${{ env.promote-from }}
